# Generated by Django 3.2.4 on 2021-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AVGRegisterline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verwerking', models.CharField(max_length=256, null=True)),
                ('applicatienaam', models.CharField(max_length=256)),
                ('naam_opslagmedium', models.CharField(max_length=256)),
                ('doel_van_de_verwerking', models.TextField()),
                ('rechtmatige_grondslag', models.CharField(max_length=256)),
                ('opmerkingen', models.TextField()),
                ('eigenaar', models.CharField(max_length=256)),
                ('beheerders', models.CharField(max_length=256)),
                ('betrokkenen', models.CharField(max_length=256)),
                ('inschatting_aantal_betrokkenen', models.CharField(max_length=256, verbose_name='# betrokkenen')),
                ('registratie_van_NAW_gegevens', models.BooleanField(null=True)),
                ('registratie_van_genderinformatie', models.BooleanField(null=True)),
                ('registratie_van_geboortedatum', models.BooleanField(null=True)),
                ('registratie_van_geboorteplaats', models.BooleanField(null=True)),
                ('registratie_van_nationaliteit', models.BooleanField(null=True)),
                ('registratie_van_IBAN_nummer', models.BooleanField(null=True)),
                ('verwerking_van_foto', models.BooleanField(null=True)),
                ('registratie_van_emailadres', models.BooleanField(null=True)),
                ('registratie_van_telefoonnummer', models.BooleanField(null=True)),
                ('registratie_van_identificatiebewijs', models.BooleanField(null=True)),
                ('registratie_van_BSN_nummer', models.BooleanField(null=True)),
                ('registratie_van_studienummer', models.BooleanField(null=True)),
                ('registratie_van_personeelsnummer', models.BooleanField(null=True)),
                ('registratie_van_videobeeldinformatie', models.BooleanField(null=True)),
                ('registratie_van_geluidsinformatie', models.BooleanField(null=True)),
                ('registratie_van_locatie_informatie', models.BooleanField(null=True)),
                ('registratie_van_financiële_informatie', models.BooleanField(null=True)),
                ('registratie_van_burgerlijke_staat', models.BooleanField(null=True)),
                ('registratie_van_gezinssamenstelling', models.BooleanField(null=True)),
                ('registratie_van_lidmaatschap_van_een_vakbond', models.BooleanField(null=True)),
                ('registratie_van_strafrechtelijke_gegevens', models.BooleanField(null=True)),
                ('registratie_van_gezondheidsgegevens', models.BooleanField(null=True)),
                ('registratie_van_opleidingsinformatie', models.BooleanField(null=True)),
                ('registratie_van_functie_informatie', models.BooleanField(null=True)),
                ('registratie_van_seksuele_geaardheid', models.BooleanField(null=True)),
                ('registratie_van_politieke_voorkeur', models.BooleanField(null=True)),
                ('registratie_van_religie', models.BooleanField(null=True)),
                ('registratie_van_genetische_informatie', models.BooleanField(null=True)),
                ('registratie_van_biometrische_informatie', models.BooleanField(null=True)),
                ('andere_categorieën_persoonsgegevens', models.CharField(max_length=256)),
                ('naam_verwerker', models.CharField(max_length=256)),
                ('verwerkersovereenkomst', models.BooleanField(null=True)),
                ('ontvangers', models.CharField(max_length=256)),
                ('in_welke_landen_worden_de_gegevens_verwerkt', models.CharField(max_length=256)),
                ('vestigingsland_van_de_verwerker', models.CharField(max_length=256)),
                ('bewaartermijn', models.TextField()),
                ('beveiligingsmaatregelen_die_genomen_worden_om_de_gegevens_te_beveiligen', models.TextField(db_column='beveiligingsmaatregelen')),
                ('bron_waar_de_gegevens_worden_verkregen', models.CharField(max_length=256)),
                ('DPIA_uitgevoerd', models.BooleanField(null=True)),
                ('bevat_persoonsgegevens', models.BooleanField(null=True)),
            ],
        ),
    ]
