# Generated by Django 3.2.7 on 2021-09-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AVGRegisterline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verwerking', models.CharField(blank=True, max_length=256, null=True)),
                ('applicatienaam', models.CharField(blank=True, max_length=256)),
                ('naam_opslagmedium', models.CharField(blank=True, max_length=256)),
                ('doel_van_de_verwerking', models.TextField(blank=True)),
                ('rechtmatige_grondslag', models.CharField(blank=True, max_length=256)),
                ('opmerkingen', models.TextField(blank=True)),
                ('eigenaar', models.CharField(blank=True, max_length=256)),
                ('beheerders', models.CharField(blank=True, max_length=256)),
                ('betrokkenen', models.CharField(blank=True, max_length=256)),
                ('inschatting_aantal_betrokkenen', models.CharField(blank=True, max_length=256, verbose_name='# betrokkenen')),
                ('registratie_van_NAW_gegevens', models.BooleanField(blank=True, null=True)),
                ('registratie_van_genderinformatie', models.BooleanField(blank=True, null=True)),
                ('registratie_van_geboortedatum', models.BooleanField(blank=True, null=True)),
                ('registratie_van_geboorteplaats', models.BooleanField(blank=True, null=True)),
                ('registratie_van_nationaliteit', models.BooleanField(blank=True, null=True)),
                ('registratie_van_IBAN_nummer', models.BooleanField(blank=True, null=True)),
                ('verwerking_van_foto', models.BooleanField(blank=True, null=True)),
                ('registratie_van_emailadres', models.BooleanField(blank=True, null=True)),
                ('registratie_van_telefoonnummer', models.BooleanField(blank=True, null=True)),
                ('registratie_van_identificatiebewijs', models.BooleanField(blank=True, null=True)),
                ('registratie_van_BSN_nummer', models.BooleanField(blank=True, null=True)),
                ('registratie_van_studienummer', models.BooleanField(blank=True, null=True)),
                ('registratie_van_personeelsnummer', models.BooleanField(blank=True, null=True)),
                ('registratie_van_videobeeldinformatie', models.BooleanField(blank=True, null=True)),
                ('registratie_van_geluidsinformatie', models.BooleanField(blank=True, null=True)),
                ('registratie_van_locatie_informatie', models.BooleanField(blank=True, null=True)),
                ('registratie_van_financiële_informatie', models.BooleanField(blank=True, null=True)),
                ('registratie_van_burgerlijke_staat', models.BooleanField(blank=True, null=True)),
                ('registratie_van_gezinssamenstelling', models.BooleanField(blank=True, null=True)),
                ('registratie_van_lidmaatschap_van_een_vakbond', models.BooleanField(blank=True, null=True)),
                ('registratie_van_strafrechtelijke_gegevens', models.BooleanField(blank=True, null=True)),
                ('registratie_van_gezondheidsgegevens', models.BooleanField(blank=True, null=True)),
                ('registratie_van_opleidingsinformatie', models.BooleanField(blank=True, null=True)),
                ('registratie_van_functie_informatie', models.BooleanField(blank=True, null=True)),
                ('registratie_van_seksuele_geaardheid', models.BooleanField(blank=True, null=True)),
                ('registratie_van_politieke_voorkeur', models.BooleanField(blank=True, null=True)),
                ('registratie_van_religie', models.BooleanField(blank=True, null=True)),
                ('registratie_van_genetische_informatie', models.BooleanField(blank=True, null=True)),
                ('registratie_van_biometrische_informatie', models.BooleanField(blank=True, null=True)),
                ('andere_categorieën_persoonsgegevens', models.TextField(blank=True)),
                ('naam_verwerker', models.CharField(blank=True, max_length=256)),
                ('verwerkersovereenkomst', models.BooleanField(blank=True, null=True)),
                ('ontvangers', models.CharField(blank=True, max_length=256)),
                ('in_welke_landen_worden_de_gegevens_verwerkt', models.CharField(blank=True, max_length=256)),
                ('vestigingsland_van_de_verwerker', models.CharField(blank=True, max_length=256)),
                ('bewaartermijn', models.TextField()),
                ('beveiligingsmaatregelen_die_genomen_worden_om_de_gegevens_te_beveiligen', models.TextField(blank=True, db_column='beveiligingsmaatregelen')),
                ('bron_waar_de_gegevens_worden_verkregen', models.CharField(blank=True, max_length=256)),
                ('DPIA_uitgevoerd', models.BooleanField(blank=True, null=True)),
                ('bevat_persoonsgegevens', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharepointExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('sourcekey', models.CharField(max_length=128)),
                ('last_updated', models.DateTimeField(null=True)),
                ('avgregisterline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_reference', to='core.avgregisterline')),
            ],
        ),
    ]
