# Generated by Django 3.2.4 on 2021-06-12 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('core', '0002_sharepointexcelfile'), ('core', '0003_sharepointexcelfile_uploaded'), ('core', '0004_alter_avgregisterline_andere_categorieën_persoonsgegevens'), ('core', '0005_alter_avgregisterline_unique_together'), ('core', '0006_alter_avgregisterline_unique_together')]

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharepointExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='andere_categorieën_persoonsgegevens',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='avgregisterline',
            unique_together=set(),
        ),
    ]
