# Generated by Django 3.2.4 on 2021-10-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_externalreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgregisterline',
            name='DPIA_uitgevoerd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='andere_categorieën_persoonsgegevens',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='applicatienaam',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='beheerders',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='betrokkenen',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='bevat_persoonsgegevens',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='beveiligingsmaatregelen_die_genomen_worden_om_de_gegevens_te_beveiligen',
            field=models.TextField(blank=True, db_column='beveiligingsmaatregelen'),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='bewaartermijn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='bron_waar_de_gegevens_worden_verkregen',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='doel_van_de_verwerking',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='eigenaar',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='in_welke_landen_worden_de_gegevens_verwerkt',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='inschatting_aantal_betrokkenen',
            field=models.CharField(blank=True, max_length=256, verbose_name='# betrokkenen'),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='naam_opslagmedium',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='naam_verwerker',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='ontvangers',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='opmerkingen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='rechtmatige_grondslag',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_BSN_nummer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_IBAN_nummer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_NAW_gegevens',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_biometrische_informatie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_burgerlijke_staat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_emailadres',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_financiële_informatie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_functie_informatie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_geboortedatum',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_geboorteplaats',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_geluidsinformatie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_genderinformatie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_genetische_informatie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_gezinssamenstelling',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_gezondheidsgegevens',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_identificatiebewijs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_lidmaatschap_van_een_vakbond',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_locatie_informatie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_nationaliteit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_opleidingsinformatie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_personeelsnummer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_politieke_voorkeur',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_religie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_seksuele_geaardheid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_strafrechtelijke_gegevens',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_studienummer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_telefoonnummer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='registratie_van_videobeeldinformatie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='verwerkersovereenkomst',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='verwerking',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='verwerking_van_foto',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgregisterline',
            name='vestigingsland_van_de_verwerker',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='externalreference',
            name='avgregisterline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externals', to='core.avgregisterline'),
        ),
    ]
